name: Test Review App on Heroku

on:
  pull_request:

jobs:
  test-review-app:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Test Dependencies
        run: poetry install --no-root --no-interaction
      - name: Ensure Review App Builds
        id: review_app_test 
        uses: niteoweb/reviewapps-deploy-status@v1.4.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        env:
          MOZ_HEADLESS: 1
        run: |
          poetry run pytest \
            --driver Firefox \
            --base-url ${{ steps.review_app_test.outputs.review_app_url }}
